"""initial

Revision ID: 1b77538f60bd
Revises: 
Create Date: 2026-05-08 20:19:42.439737

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1b77538f60bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_locations', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('current_locations', sa.Column('lng', sa.Float(), nullable=False))
    op.drop_index('ix_current_location_group', table_name='current_locations')
    op.drop_constraint('uq_current_location_user_group', 'current_locations', type_='unique')
    op.create_index(op.f('ix_current_locations_group_id'), 'current_locations', ['group_id'], unique=False)
    op.create_index(op.f('ix_current_locations_user_id'), 'current_locations', ['user_id'], unique=False)
    op.create_unique_constraint('uq_current_location', 'current_locations', ['user_id', 'group_id'])
    op.drop_column('current_locations', 'longitude')
    op.drop_column('current_locations', 'latitude')
    op.drop_constraint('group_members_group_id_user_id_key', 'group_members', type_='unique')
    op.create_unique_constraint('uq_group_member', 'group_members', ['group_id', 'user_id'])
    op.add_column('location_history', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('location_history', sa.Column('lng', sa.Float(), nullable=False))
    op.drop_index('ix_location_history_user_group', table_name='location_history')
    op.create_index(op.f('ix_location_history_group_id'), 'location_history', ['group_id'], unique=False)
    op.create_index(op.f('ix_location_history_user_id'), 'location_history', ['user_id'], unique=False)
    op.drop_column('location_history', 'longitude')
    op.drop_column('location_history', 'latitude')
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.add_column('location_history', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('location_history', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_location_history_user_id'), table_name='location_history')
    op.drop_index(op.f('ix_location_history_group_id'), table_name='location_history')
    op.create_index('ix_location_history_user_group', 'location_history', ['user_id', 'group_id'], unique=False)
    op.drop_column('location_history', 'lng')
    op.drop_column('location_history', 'lat')
    op.drop_constraint('uq_group_member', 'group_members', type_='unique')
    op.create_unique_constraint('group_members_group_id_user_id_key', 'group_members', ['group_id', 'user_id'])
    op.add_column('current_locations', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('current_locations', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('uq_current_location', 'current_locations', type_='unique')
    op.drop_index(op.f('ix_current_locations_user_id'), table_name='current_locations')
    op.drop_index(op.f('ix_current_locations_group_id'), table_name='current_locations')
    op.create_unique_constraint('uq_current_location_user_group', 'current_locations', ['user_id', 'group_id'])
    op.create_index('ix_current_location_group', 'current_locations', ['group_id'], unique=False)
    op.drop_column('current_locations', 'lng')
    op.drop_column('current_locations', 'lat')
    # ### end Alembic commands ###
